### ISSUE TITLE
Infinite iota -> filter -> transform

### ISSUE THREAD

**Issue by BRevzin** [CaseyCarter/cmcstl2#262] opened 2019-01-04 18:43 UTC
From [StackOverflow](https://stackoverflow.com/q/54044313/2069064):

```cpp
#include <experimental/ranges/ranges>

int main() {
    using namespace std::experimental::ranges::view;
    auto id = [](int x){ return x; };

    // these compile
    iota(0,100) | filter(id) | transform(id);
    iota(0) | transform(id) | filter(id);

    iota(0) | transform(id);
    iota(0) | filter(id);

    // this one doesn't compile
    iota(0) | filter(id) | transform(id);
}
```

The top-level compile error I get is:

```
cmcstl2/include/stl2/detail/range/access.hpp: In instantiation of ‘class std::experimental::ranges::v1::transform_view<std::experimental::ranges::v1::filter_view<std::experimental::ranges::v1::iota_view<int, std::experimental::ranges::v1::unreachable>, main()::<lambda(int)> >, main()::<lambda(int)> >::__sentinel<false>’:
cmcstl2/include/stl2/detail/range/access.hpp:119:19:   required by substitution of ‘template<class Rng> constexpr decltype (c(forward<Rng>(rng))) std::experimental::ranges::v1::detail::operator|(Rng&&, const std::experimental::ranges::v1::detail::view_closure<std::experimental::ranges::v1::view::__transform_fn, main()::<lambda(int)> >&) [with Rng = std::experimental::ranges::v1::filter_view<std::experimental::ranges::v1::iota_view<int, std::experimental::ranges::v1::unreachable>, main()::<lambda(int)> >]’
ex.cxx:12:40:   required from here
cmcstl2/include/stl2/detail/range/access.hpp:169:30: error: no match for call to ‘(const std::experimental::ranges::v1::__end::__fn) (const std::experimental::ranges::v1::filter_view<std::experimental::ranges::v1::iota_view<int, std::experimental::ranges::v1::unreachable>, main()::<lambda(int)> >&)’
  using __end_t = decltype(end(std::declval<R>()));
                           ~~~^~~~~~~~~~~~~~~~~~~
```

**Comment by CaseyCarter** [comment] 2019-01-05 00:13
The problem is instantiating the `__sentinel<false>` converting constructor:
```c++
constexpr __sentinel(__sentinel<!Const> i)
requires Const && ConvertibleTo<sentinel_t<R>, sentinel_t<const R>>
: end_(i.end_) {}
```
GCC is over-eagerly substituting `sentinel_t<const R>` despite that `Const` is `false`.

**Comment by CaseyCarter** [comment] 2019-01-05 00:39
Fixed by 1c5142aed93167f16142b51f61e2ac081d05de58.

**Closed by CaseyCarter** 2019-01-05 00:39 UTC
Labels: bug
