### ISSUE TITLE
CopyConstructible<vector<unique_ptr<int>>> is true

### ISSUE THREAD

**Issue by cjdb** [CaseyCarter/cmcstl2#141] opened 2018-03-24 09:37 UTC
... but is `vector<unique_ptr<int>>` is not copy-constructible. Link: https://godbolt.org/g/4Kvvm3.

This might be related to a3abeb89d93ae9ff040235c1705ec50753d09c68.

**Comment by CaseyCarter** [comment] 2018-03-24 14:36
This is effectively a duplicate of #142.

**Closed by CaseyCarter** 2018-03-24 14:36 UTC
